### ISSUE TITLE
Can't get the model file.

### ISSUE THREAD

**Issue by yinjie10086** [cafebabei/nsfw-image-classification#1]
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by Armon2023** [comment]
你可以通过这个链接下载项目的压缩包 http://speedtail.fun/download/nsfw-image-classification.zip

**Comment by yinjie10086** [comment]
Hi,您好~这个链接也无法下载，403 Forbidden...可以提供一下别的下载方式吗

**Comment by yinjie10086** [comment]
Hi，您好~


&nbsp;下面的连接无法下载（403 Forbidden）.可否提供一下其他的下载方式~




&nbsp; 感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cafebabei/nsfw-image-classification"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 下午2:02
收件人:&nbsp;"cafebabei/nsfw-image-classification"<nsfw-image-classification@noreply.github.com&gt;;
抄送:&nbsp;"Joey"<1037177743@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cafebabei/nsfw-image-classification] Can't get the model file. (#1)





 
你可以通过这个链接下载项目的压缩包 http://speedtail.fun/download/nsfw-image-classification.zip

**Comment by Armon2023** [comment]
现在可以下载了，你再试下

**Comment by hhsummerwind** [comment]
> 现在可以下载了，你再试下

您好，现在已经不能下载了，可以重新分享一下吗？
